### ISSUE TITLE
Serielle Schnittstelle prüfen

### ISSUE THREAD

**Issue by Chrisego2** [Jey-Cee/ioBroker.enocean#71]
**Describe the bug**  
Die Serielle Schnittstelle funktioniert nach update auf 0.4.0 nicht mehr. 
In den Einstellungen lässt sich kein "Device" einstellen.

Bei erneuter Installation von 0.3.8 klappt wieder alles. 
Als Beginner schließe ich einen Anwenderfehler nicht aus. 

![grafik](https://user-images.githubusercontent.com/87148446/126077952-f366f9bf-1f28-42b8-816c-3afa937bf10d.png)

**Comment by imp3r4t0r** [comment]
Ich kann das Problem bestätigen. Habe auch auf einen 0.3.8er Commit zurückgerollt. Damit geht's wieder.
Ich habe mit ein paar Änderungen in den Commits angesehen, aber leider keinen wirklichen Hinweis auf das Problem finden können.

**Comment by Jey-Cee** [comment]
Es gibt Version 0.4.2 hast du, @imp3r4t0r,  getestet?

**Comment by imp3r4t0r** [comment]
Ja, ich habe den letzten Build von gestern (müsste 0.4.2 sein) direkt von beliebig https://github.com/Jey-Cee/ioBroker.enocean installiert. Damit hat es nicht funktioniert. Ich habe alternativ auch den https://github.com/Jey-Cee/ioBroker.enocean/commit/4e4e409f8679bd102f2878bc0ff50f34f573239f getestet. Damit ging es auch nicht.

**Comment by Jey-Cee** [comment]
Leider kann ich das Absolut nicht Nachvollziehen, auch nachdem ich 3 verschiedene Setups gemacht habe.

Bitte gebt mir mal Zusätzliche Infos:
- Log
- Admin version
- nodejs version
- js-controller version

**Comment by imp3r4t0r** [comment]
Danke schon mal für deine Bemühungen.

Ich hab folgendes Setup:

- Node.js: 14.16.1
- NPM: 6.14.12
- Admin: 4.2.2
- js-controller: 3.2.16

**Log inkl. Installation:**
2021-07-25 11:13:24.299 - info: host.srv-iobroker iobroker url "https://github.com/Jey-Cee/ioBroker.enocean"
2021-07-25 11:13:25.452 - info: host.srv-iobroker iobroker install Jey-Cee/ioBroker.enocean#da66192269b43271567d0e393d945f884e89ddaa
2021-07-25 11:13:25.596 - info: host.srv-iobroker iobroker NPM version: 6.14.12npm install Jey-Cee/ioBroker.enocean#da66192269b43271567d0e393d945f884e89ddaa --loglevel error --prefix "/opt/iobroker" (System call)
2021-07-25 11:13:42.513 - info: host.srv-iobroker iobroker upload [6] enocean.admin /opt/iobroker/node_modules/iobroker.enocean/admin/words.js words.js application/javascript
2021-07-25 11:13:42.584 - info: host.srv-iobroker iobroker upload [5] enocean.admin /opt/iobroker/node_modules/iobroker.enocean/admin/style.css style.css text/css
2021-07-25 11:13:42.637 - info: host.srv-iobroker iobroker upload [4] enocean.admin /opt/iobroker/node_modules/iobroker.enocean/admin/index_m.html index_m.html text/html
2021-07-25 11:13:42.690 - info: host.srv-iobroker iobroker upload [3] enocean.admin /opt/iobroker/node_modules/iobroker.enocean/admin/github.js github.js application/javascript
2021-07-25 11:13:42.743 - info: host.srv-iobroker iobroker upload [2] enocean.admin /opt/iobroker/node_modules/iobroker.enocean/admin/enocean.png enocean.png image/png
2021-07-25 11:13:42.796 - info: host.srv-iobroker iobroker upload [1] enocean.admin /opt/iobroker/node_modules/iobroker.enocean/admin/components.js components.js application/javascript
2021-07-25 11:13:42.850 - info: host.srv-iobroker iobroker upload [0] enocean.admin /opt/iobroker/node_modules/iobroker.enocean/admin/admin.d.ts admin.d.ts video/mp2t
2021-07-25 11:13:42.922 - info: host.srv-iobroker iobroker Update "system.adapter.enocean.0"
2021-07-25 11:13:42.936 - info: host.srv-iobroker stopInstance system.adapter.enocean.0 (force=false, process=true)
2021-07-25 11:13:42.940 - info: enocean.0 (21694) Got terminate signal TERMINATE_YOURSELF
2021-07-25 11:13:42.940 - info: enocean.0 (21694) cleaned everything up...
2021-07-25 11:13:42.941 - info: enocean.0 (21694) terminating
2021-07-25 11:13:42.941 - info: enocean.0 (21694) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2021-07-25 11:13:42.942 - info: host.srv-iobroker stopInstance system.adapter.enocean.0 send kill signal
2021-07-25 11:13:42.953 - info: enocean.0 (21694) The serial port was closed.
2021-07-25 11:13:43.480 - info: host.srv-iobroker instance system.adapter.enocean.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2021-07-25 11:13:43.951 - info: host.srv-iobroker iobroker exit 0
2021-07-25 11:13:44.312 - info: host.srv-iobroker Updating repository "Stable (default)" under "http://download.iobroker.net/sources-dist.json"
2021-07-25 11:13:46.053 - info: host.srv-iobroker instance system.adapter.enocean.0 started with pid 134521
2021-07-25 11:13:46.520 - info: enocean.0 (134521) starting. Version 0.5.0 in /opt/iobroker/node_modules/iobroker.enocean, node: v14.16.1, js-controller: 3.2.16
**2021-07-25 11:13:46.755 - error: enocean.0 (134521) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-07-25 11:13:46.755 - error: enocean.0 (134521) unhandled promise rejection: Cannot read property 'length' of undefined
2021-07-25 11:13:46.755 - error: enocean.0 (134521) TypeError: Cannot read property 'length' of undefined
at Enocean.getGatewayInfo (/opt/iobroker/node_modules/iobroker.enocean/main.js:611:32)
at async SerialPort. (/opt/iobroker/node_modules/iobroker.enocean/main.js:423:4)
2021-07-25 11:13:46.755 - error: enocean.0 (134521) Cannot read property 'length' of undefined**
2021-07-25 11:13:46.762 - info: enocean.0 (134521) cleaned everything up...
2021-07-25 11:13:46.763 - info: enocean.0 (134521) terminating
2021-07-25 11:13:46.763 - warn: enocean.0 (134521) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-07-25 11:13:46.774 - info: enocean.0 (134521) The serial port was closed.
**2021-07-25 11:13:47.297 - error: host.srv-iobroker instance system.adapter.enocean.0 terminated with code 6 (UNCAUGHT_EXCEPTION)**
2021-07-25 11:13:47.297 - info: host.srv-iobroker Restart adapter system.adapter.enocean.0 because enabled

**Comment by guergen1** [comment]
Auch bei V0.5.0 keine Serielle Schnittstelle auswählbar:
Node.js 12.22.2
NPM 6.14.13
Admin 5.1.14
js-controller 3.3.14
Nach dem einspielen des Proxmox-Backups /Enocean läuft bei mir auf einem Slave) wird trotz Installation der 0.2.1 die 0.5.0 in der Instanzen-Seite angezeigt:
![grafik](https://user-images.githubusercontent.com/34395245/126897701-e28088b9-2163-46a6-bd19-18923d4c31f8.png)
![grafik](https://user-images.githubusercontent.com/34395245/126897711-241e0d70-bdd5-48c3-9b70-6ea5f14f640a.png)

**Comment by Chrisego2** [comment]
Achtung Anfänger, in meinen Möglichkeiten versuche ich euch zu unterstützen...
hatte eben auch die V0.5.0 geteste. 
Nach Neustart Raspi war die Serielle schnittstelle auswählbar.  Adapter kam aber nicht zum laufen. info	(2031) The serial port was closed.
Rollback auf V 0.3.8 hat nicht funktioniert.  (Adapter bleibt auf  v0.5.0)

Ich hab folgendes Setup:
•	Node.js: 12.22.1
•	NPM: 6.14.12
•	Admin: 4.2.2
•	js-controller = Script Engine? --> 5.1.3

enocean.0	2021-07-25 13:03:03.390	warn	(2497) Terminated (UNCAUGHT_EXCEPTION): Without reason
enocean.0	2021-07-25 13:03:03.389	info	(2497) terminating
enocean.0	2021-07-25 13:03:03.388	info	(2497) cleaned everything up...
enocean.0	2021-07-25 13:03:03.374	error	(2497) Exception-Code: ECONNREFUSED: connect ECONNREFUSED 192.168.158.128:5000
enocean.0	2021-07-25 13:03:03.374	error	(2497) Error: connect ECONNREFUSED 192.168.158.128:5000 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
enocean.0	2021-07-25 13:03:03.372	error	(2497) uncaught exception: connect ECONNREFUSED 192.168.158.128:5000
enocean.0	2021-07-25 13:03:03.123	info	(2497) starting. Version 0.5.0 in /opt/iobroker/node_modules/iobroker.enocean, node: v12.22.1, js-controller: 3.2.16
enocean.0	2021-07-25 13:02:30.888	warn	(2381) Terminated (UNCAUGHT_EXCEPTION): Without reason
enocean.0	2021-07-25 13:02:30.887	info	(2381) terminating
enocean.0	2021-07-25 13:02:30.886	info	(2381) cleaned everything up...
enocean.0	2021-07-25 13:02:30.874	error	(2381) Exception-Code: ECONNREFUSED: connect ECONNREFUSED 192.168.158.128:5000
enocean.0	2021-07-25 13:02:30.874	error	(2381) Error: connect ECONNREFUSED 192.168.158.128:5000 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
enocean.0	2021-07-25 13:02:30.873	error	(2381) uncaught exception: connect ECONNREFUSED 192.168.158.128:5000
enocean.0	2021-07-25 13:02:30.629	info	(2381) starting. Version 0.5.0 in /opt/iobroker/node_modules/iobroker.enocean, node: v12.22.1, js-controller: 3.2.16
enocean.0	2021-07-25 13:01:58.238	warn	(2244) Terminated (UNCAUGHT_EXCEPTION): Without reason
enocean.0	2021-07-25 13:01:58.237	info	(2244) terminating
enocean.0	2021-07-25 13:01:58.236	info	(2244) cleaned everything up...
enocean.0	2021-07-25 13:01:58.224	error	(2244) Exception-Code: ECONNREFUSED: connect ECONNREFUSED 192.168.158.128:5000
enocean.0	2021-07-25 13:01:58.223	error	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
enocean.0	2021-07-25 13:01:58.223	error	(2244) Error: connect ECONNREFUSED 192.168.158.128:5000
enocean.0	2021-07-25 13:01:58.222	error	(2244) uncaught exception: connect ECONNREFUSED 192.168.158.128:5000
enocean.0	2021-07-25 13:01:57.927	info	(2244) starting. Version 0.5.0 in /opt/iobroker/node_modules/iobroker.enocean, node: v12.22.1, js-controller: 3.2.16
enocean.0	2021-07-25 12:58:22.051	info	(2031) The serial port was closed.
enocean.0	2021-07-25 12:58:22.046	warn	(2031) Terminated (UNCAUGHT_EXCEPTION): Without reason
enocean.0	2021-07-25 12:58:22.045	info	(2031) terminating
enocean.0	2021-07-25 12:58:22.044	info	(2031) cleaned everything up...
enocean.0	2021-07-25 12:58:22.030	error	(2031) Cannot read property 'length' of undefined
enocean.0	2021-07-25 12:58:22.030	error	at async SerialPort.<anonymous> (/opt/iobroker/node_modules/iobroker.enocean/main.js:423:4)
enocean.0	2021-07-25 12:58:22.030	error	at Enocean.getGatewayInfo (/opt/iobroker/node_modules/iobroker.enocean/main.js:611:32)
enocean.0	2021-07-25 12:58:22.030	error	(2031) TypeError: Cannot read property 'length' of undefined
enocean.0	2021-07-25 12:58:22.029	error	(2031) unhandled promise rejection: Cannot read property 'length' of undefined
enocean.0	2021-07-25 12:58:22.028	error	(2031) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
enocean.0	2021-07-25 12:58:21.692	info	(2031) starting. Version 0.5.0 in /opt/iobroker/node_modules/iobroker.enocean, node: v12.22.1, js-controller: 3.2.16
enocean.0	2021-07-25 12:57:49.334	info	(2014) The serial port was closed.
enocean.0	2021-07-25 12:57:49.328	warn	(2014) Terminated (UNCAUGHT_EXCEPTION): Without reason
enocean.0	2021-07-25 12:57:49.327	info	(2014) terminating
enocean.0	2021-07-25 12:57:49.326	info	(2014) cleaned everything up...
enocean.0	2021-07-25 12:57:49.310	error	(2014) Cannot read property 'length' of undefined
enocean.0	2021-07-25 12:57:49.310	error	at async SerialPort.<anonymous> (/opt/iobroker/node_modules/iobroker.enocean/main.js:423:4)
enocean.0	2021-07-25 12:57:49.310	error	at Enocean.getGatewayInfo (/opt/iobroker/node_modules/iobroker.enocean/main.js:611:32)
enocean.0	2021-07-25 12:57:49.310	error	(2014) TypeError: Cannot read property 'length' of undefined
enocean.0	2021-07-25 12:57:49.309	error	(2014) unhandled promise rejection: Cannot read property 'length' of undefined
enocean.0	2021-07-25 12:57:49.308	error	(2014) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
enocean.0	2021-07-25 12:57:48.972	info	(2014) starting. Version 0.5.0 in /opt/iobroker/node_modules/iobroker.enocean, node: v12.22.1, js-controller: 3.2.16
enocean.0	2021-07-25 12:57:16.682	info	(1966) The serial port was closed.
enocean.0	2021-07-25 12:57:16.679	warn	(1966) Terminated (UNCAUGHT_EXCEPTION): Without reason
enocean.0	2021-07-25 12:57:16.678	info	(1966) terminating
enocean.0	2021-07-25 12:57:16.677	info	(1966) cleaned everything up...
enocean.0	2021-07-25 12:57:16.658	error	(1966) Cannot read property 'length' of undefined
enocean.0	2021-07-25 12:57:16.657	error	at async SerialPort.<anonymous> (/opt/iobroker/node_modules/iobroker.enocean/main.js:423:4)
enocean.0	2021-07-25 12:57:16.657	error	at Enocean.getGatewayInfo (/opt/iobroker/node_modules/iobroker.enocean/main.js:611:32)
enocean.0	2021-07-25 12:57:16.657	error	(1966) TypeError: Cannot read property 'length' of undefined
enocean.0	2021-07-25 12:57:16.656	error	(1966) unhandled promise rejection: Cannot read property 'length' of undefined
enocean.0	2021-07-25 12:57:16.656	error	(1966) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
enocean.0	2021-07-25 12:57:15.966	info	(1966) starting. Version 0.5.0 in /opt/iobroker/node_modules/iobroker.enocean, node: v12.22.1, js-controller: 3.2.16
enocean.0	2021-07-25 12:57:13.525	warn	(1925) get state error: DB closed
enocean.0	2021-07-25 12:57:13.522	warn	(1925) get state error: Connection is closed.
enocean.0	2021-07-25 12:57:13.513	info	(1925) The serial port was closed.
enocean.0	2021-07-25 12:57:12.635	warn	(1925) An error occured at serial port: Error: Port is not open
enocean.0	2021-07-25 12:57:12.634	warn	(1925) Error sending data: Error: Port is not open
enocean.0	2021-07-25 12:57:11.287	info	(1925) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
enocean.0	2021-07-25 12:57:11.286	info	(1925) terminating
enocean.0	2021-07-25 12:57:11.285	info	(1925) cleaned everything up...
enocean.0	2021-07-25 12:57:11.282	info	(1925) Got terminate signal TERMINATE_YOURSELF
enocean.0	2021-07-25 12:57:02.239	info	(1925) ["/dev/ttyAMA0","/dev/ttyUSB0"]
enocean.0	2021-07-25 12:52:32.623	info	(1925) starting. Version 0.5.0 in /opt/iobroker/node_modules/iobroker.enocean, node: v12.22.1, js-controller: 3.2.16
enocean.0	2021-07-25 12:52:27.898	info	(1131) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
enocean.0	2021-07-25 12:52:27.897	info	(1131) terminating
enocean.0	2021-07-25 12:52:27.896	info	(1131) cleaned everything up...
enocean.0	2021-07-25 12:52:27.894	info	(1131) Got terminate signal TERMINATE_YOURSELF
enocean.0	2021-07-25 12:52:16.525	info	(1131) ["/dev/ttyAMA0","/dev/ttyUSB0"]


host.HomeGoldbrunner	2021-07-25 12:58:22.698	warn	Do not restart adapter system.adapter.enocean.0 because restart loop detected
host.HomeGoldbrunner	2021-07-25 12:58:22.697	info	Restart adapter system.adapter.enocean.0 because enabled
host.HomeGoldbrunner	2021-07-25 12:58:22.697	error	instance system.adapter.enocean.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.HomeGoldbrunner	2021-07-25 12:58:20.017	info	instance system.adapter.enocean.0 started with pid 2031
host.HomeGoldbrunner	2021-07-25 12:57:49.972	info	Restart adapter system.adapter.enocean.0 because enabled
host.HomeGoldbrunner	2021-07-25 12:57:49.971	error	instance system.adapter.enocean.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.HomeGoldbrunner	2021-07-25 12:57:47.321	info	instance system.adapter.enocean.0 started with pid 2014
host.HomeGoldbrunner	2021-07-25 12:57:17.269	info	Restart adapter system.adapter.enocean.0 because enabled
host.HomeGoldbrunner	2021-07-25 12:57:17.268	error	instance system.adapter.enocean.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.HomeGoldbrunner	2021-07-25 12:57:14.422	info	instance system.adapter.enocean.0 started with pid 1966
host.HomeGoldbrunner	2021-07-25 12:57:13.661	info	instance system.adapter.enocean.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.HomeGoldbrunner	2021-07-25 12:57:12.284	info	stopInstance system.adapter.enocean.0 killing pid 1925
host.HomeGoldbrunner	2021-07-25 12:57:11.282	info	stopInstance system.adapter.enocean.0 send kill signal
host.HomeGoldbrunner	2021-07-25 12:57:11.271	info	stopInstance system.adapter.enocean.0 (force=false, process=true)
host.HomeGoldbrunner	2021-07-25 12:52:30.962	info	instance system.adapter.enocean.0 started with pid 1925
host.HomeGoldbrunner	2021-07-25 12:52:28.535	info	instance system.adapter.enocean.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.HomeGoldbrunner	2021-07-25 12:52:27.903	info	stopInstance system.adapter.enocean.0 send kill signal
host.HomeGoldbrunner	2021-07-25 12:52:27.891	info	stopInstance system.adapter.enocean.0 (force=false, process=true)
host.HomeGoldbrunner	2021-07-25 12:51:57.025	info	instance system.adapter.tr-064.0 started with pid 1910
host.HomeGoldbrunner	2021-07-25 12:51:52.990	info	instance system.adapter.telegram.0 started with pid 1895
host.HomeGoldbrunner	2021-07-25 12:51:49.004	info	instance system.adapter.sonoff.0 started with pid 1880
host.HomeGoldbrunner	2021-07-25 12:51:45.042	info	instance system.adapter.simple-api.0 started with pid 1861

**Comment by Jey-Cee** [comment]
Das Problem mit dem Absturz habe ich gefixt. 
Warum nach einem Rollback immer noch die 0.5.0 angezeigt wird kann ich nicht sagen, hat aber auch nichts mit dem Adapter selbst zu tun.

**Comment by imp3r4t0r** [comment]
Mit der 0.5.1 funktioniert es bei mir wieder! Herzlichen DANK!
