### ISSUE TITLE
FT55 both buttons pressed

### ISSUE THREAD

**Issue by hearp** [Jey-Cee/ioBroker.enocean#82]
Hi,
unfortunately the Eltako FT55 implementation doesn't recognize when both buttons are pressed.
Is there a possibility get the information, if both buttons are pressed simulatiously?

**Comment by Jey-Cee** [comment]
No not now

**Comment by KLVN** [comment]
>both buttons are pressed simulatiously

Is the FT55 even capable of sending a telegram that signals both buttons are pressed at once? Because I don't think so. You could script this functionality yourself in the JavaScript-Adapter, e.g. On click (left or right button), wait a few ms and if there's another click within that time, then both buttons are pressed; else it's only one button pressed. This way you can also implement a double/triple/... click. However, because your script will always wait for another click, you'll notice a small delay when you only want to press the button once. This requires that the FT55 can send two telegrams very close after another, if you press two buttons *simultaneously*.

**Comment by hearp** [comment]
I agree with your observation. At the moment you just get the informationen for the A channel.
In FHEM you get two aspects: Buttons (Ax or Bx or Ax,Bx) and Status (pressed or released). So it seems the device sends two telegrams, but the B channel telegram doesn't come through.

**Comment by Jey-Cee** [comment]
The following combinations are possible AI + BI, A0 + B0, AI + B0, A0 + BI. 
I wil create new datapoints for this combinations.

**Comment by Jey-Cee** [comment]
The updated code is now on Github. If you need this feature for already learned devices, you have to delete them and add again.
