### ISSUE TITLE
[Bug]: DSZ14 sometimes MR is 0

### ISSUE THREAD

**Issue by copystring** [Jey-Cee/ioBroker.enocean#87]
### Contact Details

copystring@gmail.com

### What happened?

With DSZ14 sometimes MR is 0 until next update. then it returns back to the reported kWh in the next update.
Can you make so it ignores values of 0 and return the previous value or not set the value if 0?
This is messing up the calculations of sourceanalytix.

### Adapter Version

0.5.4

### JS-Controller Version

5.2.13

### Node JS Version

12.22.6

### NPM Version

6.14.15

### Operating System

Debian

### Anything else?

![image](https://user-images.githubusercontent.com/1298861/136074880-f4178f3d-849e-4c28-bc73-b155cd7e456e.png)

How would I post a relevant log?

**Comment by copystring** [comment]
![image](https://user-images.githubusercontent.com/1298861/136086890-4fb70051-672e-4b5a-8c37-3841f57d8269.png)

**Comment by Jey-Cee** [comment]
> How would I post a relevant log?

Go to instances tab, activate expert mode and change loglevel for th instance of enocean.
Wait for data from the device which causes the problem, copy the TEXT and post it here. NO SCREENSHOT

**Comment by copystring** [comment]
> > How would I post a relevant log?
> 
> Go to instances tab, activate expert mode and change loglevel for th instance of enocean. Wait for data from the device which causes the problem, copy the TEXT and post it here. NO SCREENSHOT

Sure. Like this? https://pastebin.com/wU3ESiud

**Comment by Jey-Cee** [comment]
This is happen because there are day and night counter. I've splitted MR to DMR and NMR. 
You have to readd the DSZ14. Please check the changes.

**Comment by copystring** [comment]
Thanks. I put the latest version on my iobroker. But sometimes DMR is the same value as PC while PC is always displayed correctly. Just like it was before my pull request here: https://github.com/Jey-Cee/ioBroker.enocean/pull/86

**Comment by Jey-Cee** [comment]
Hm that makes no sense, there is a single bit which is set to 1 = PC or 0 = MR. So it can not be both at the same time.

**Comment by copystring** [comment]
Hm. Then I don't know what to do...

**Comment by copystring** [comment]
But I'm not making this up. I just deleted everything of the enocean module on iobroker. manually deleted the enocean folder in /opt/iobroker/node_modules/ and added it again by custom url with this github repo.
Configured the DSZ14 again. Waited a few seconds. Bam. DMR and PC is the same value...

![image](https://user-images.githubusercontent.com/1298861/136849021-141ee052-d647-48ce-a5e3-78efd1ce570f.png)

Here's the log that belongs to the timestamp of the screenshot: https://pastebin.com/MtcJ0E6s

**Comment by Jey-Cee** [comment]
I found the issue, it is fixed in the next version

**Comment by copystring** [comment]
Is it fixed in the current github? I loaded 0.6.4 from github to iobroker and it behaves the same as before.

**Comment by Jey-Cee** [comment]
Yes should be fixed now. Version is still 0.6.4 but the code is updated.

**Comment by copystring** [comment]
With the latest version directly from github I can't confirm the fix.

**Comment by Jey-Cee** [comment]
Please check actual version from Github.

**Comment by copystring** [comment]
Hi. I can't test this anymore since I've sold my device a while ago when we got solar panels.

**Comment by Jey-Cee** [comment]
Ok then i will close this issue. Thanks for your response

**Comment by T-o-m-D** [comment]
Hi Jey-Cee,
I can confirm, that the DMR often shows the PC value instead of the real kWh value. I have three DSZ14DRS power meters installed. Attached is some protocol info from the "Eltako_Gesamtkatalog_LowRes.pdf", a log file (look for device ID 00000050, 00000051 and 00000052), a screenshot showing that behaviour and the "debug information" from adapter settings. Feel free to ask for more information if needed.

![DSZ14 PC wrong](https://user-images.githubusercontent.com/117567276/217865321-c36242e2-34d4-4443-b30f-5db6098c90cc.PNG)
![Eltako A5-12-01 Info](https://user-images.githubusercontent.com/117567276/217865355-d226757b-f486-4d69-be1f-d0ae1dddf271.PNG)
[enocean log.txt](https://github.com/Jey-Cee/ioBroker.enocean/files/10698947/enocean.log.txt)
[support_information.txt](https://github.com/Jey-Cee/ioBroker.enocean/files/10698994/support_information.txt)

**Comment by Jey-Cee** [comment]
@T-o-m-D you have not installed the actual version from Github where it is fixed.

**Comment by T-o-m-D** [comment]
I tried the Github code a few weeks ago, but I had massive problems with all my Eltako devices, so I downgraded.
I just tried again, first impression is:
- DSZ14 is not updating any state
- FTR55HB (FHK) is setting TMP to "(null) °C", SP is working
- FWG14MS is not updating any state
- FUD14 is updating LVL, but not ON (timstamp up-to-date, but last change is not changing date)

**Comment by Jey-Cee** [comment]
Howany weeks?

**Comment by T-o-m-D** [comment]
I'm not sure, must have been at the end of last year. But maybe I wasn't using the Github version before. I can't remember the details. At some point I was frustrated because nothing worked anymore and stopped playing with iobroker/enocean until this week when I figured out, the official 0,8,4 is working way better.

I'll try to figure out a date/commit where things stopped working by installing older Github versions.

**Comment by T-o-m-D** [comment]
November, 17th: "release 0.8.4": working
Novermber, 18th: not receiving packets: not getting any "Message for ID ... received" log entries
December, 4th: message receive working again, but problems with data interpretation as stated in my previous comment.

Interesting detail: FTR55HB (FHK) is using definition TF-13-14.json. When changing the bitoffset of TMP from 16 to 15 the state successfully updates (but of course wrong value calculated). Maybe there is a length limitation of the raw source data array/bitfield for ERP2 input messages?
